sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -f latest/Dockerfile -t nodered/node-red-docker .
  - docker build -f slim/Dockerfile -t nodered/node-red-docker:slim .
  - docker tag nodered/node-red-docker nodered/node-red-docker:$VERSION
  - docker tag nodered/node-red-docker:slim nodered/node-red-docker:$VERSION-slim

script:
  - docker run -d nodered/node-red-docker:latest
  - docker ps | grep latest
  - docker run -d nodered/node-red-docker:slim
  - docker ps | grep slim

after_success:
  - docker login -e "$DOCKER_EMAIL" -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push nodered/node-red-docker

env:
  - VERSION=0.16.1
